scaling:
  properties:
    - var: flow_mol_phase_comp
      index: ["Liq", "H2O"]
      factor: 1
    - var: flow_mol_phase_comp
      index: ["Liq", "Na_+"]
      factor: 2000
    - var: flow_mol_phase_comp
      index: ["Liq", "Mg_2+"]
      factor: 50000
    - var: flow_mol_phase_comp
      index: ["Liq", "Cl_-"]
      factor: 2000
    - var: flow_mol_phase_comp
      index: ["Liq", "Ca_2+"]
      factor: 100000
    - var: flow_vol_phase
      index: ["Liq"]
      factor: 50000

  components:
    - target: fs.EDstack.cell_width
      factor: 5
    - target: fs.EDstack.cell_length
      factor: 1
    - target: fs.EDstack.cell_pair_num
      factor: 0.01
    - target: fs.EDstack.voltage_applied
      factor: 0.1
    - target: fs.EDstack.diluate.power_electrical_x
      factor: 1
    - target: fs.pump0.control_volume.work
      factor: 10
    - target: fs.pump1.control_volume.work
      factor: 10

  # constraints:
  #   -